import { SiteLink as Link } from "@/src/components/site-link";
import { PublicShell } from "@/src/components/site-shell";
import { localModules } from "@/src/repositories/local";
import { CmsPublicPageView } from "@/src/components/cms-public-page";
import { getPublishedCmsPage } from "@/src/lib/public-cms";
import { pageMetadata } from "@/src/lib/seo";
export async function generateMetadata() {
  const cmsPage = await getPublishedCmsPage("/platform");
  if (cmsPage) return pageMetadata({ title: cmsPage.seoTitle ?? cmsPage.title, description: cmsPage.seoDescription ?? "", path: "/platform", noindex: cmsPage.noindex });
  return pageMetadata({ title: "Platform voor verenigingen", description: "Eén centrale omgeving voor leden, agenda, aanwezigheid, communicatie en beheer.", path: "/platform" });
}
export default async function Platform(){const cmsPage=await getPublishedCmsPage("/platform");if(cmsPage)return <CmsPublicPageView page={cmsPage}/>;const modules=await localModules.listPublished();return <PublicShell><section className="hero"><div className="container hero-layout"><div><p className="eyebrow">Het platform</p><h1>Eén omgeving.<br/>Meer overzicht.</h1><p className="lede">Meer Vereniging brengt leden, agenda, aanwezigheid, communicatie en beheer samen. Niet als losse eilanden, maar als één rustige basis voor de vereniging.</p><div className="hero-actions"><Link className="btn btn-primary" href="/demo">Vraag een demo aan</Link><Link className="btn btn-secondary" href="/modules">Bekijk de onderdelen</Link></div></div><p className="home-hero-aside">Minder losse apps.<br/>Minder Excel.<br/>Minder zoeken.<br/><strong>Meer zicht op wat er speelt.</strong></p></div></section><section className="section"><div className="container home-practice"><div><p className="eyebrow">Van dagelijks werk naar overzicht</p><h2>Het verhaal zit in de samenhang.</h2><p className="lede">Een ledenlijst is pas nuttig als je ermee kunt plannen. Een agenda werkt pas als mensen weten wat er van ze wordt verwacht. Daarom horen deze onderdelen bij elkaar.</p></div><div className="practice-list"><article className="practice-item"><span>01</span><div><h3>Leden en teams</h3><p>Gegevens, groepen en verantwoordelijkheden vanuit dezelfde actuele basis.</p></div></article><article className="practice-item"><span>02</span><div><h3>Agenda en aanwezigheid</h3><p>Van repetitie tot wedstrijd: afspraken en reacties op één plek.</p></div></article><article className="practice-item"><span>03</span><div><h3>Communicatie en beheer</h3><p>Rollen, rechten en berichten die passen bij hoe je vereniging werkt.</p></div></article></div></div></section><section className="section section-mist"><div className="container"><p className="eyebrow">Onderdelen van één platform</p><h2>Alles werkt samen.</h2><div className="module-list">{modules.map((module,index)=><Link className="module-row" href={`/modules/${module.slug}`} key={module.id}><span className="module-index">{String(index+1).padStart(2,"0")}</span><h3>{module.name}</h3><p>{module.shortDescription}</p><span className="btn-quiet">Meer over {module.name}</span></Link>)}</div></div></section></PublicShell>}
