import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
async function render(path="/"){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${Date.now()}-${path}`);const {default:worker}=await import(workerUrl.href);return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}})}
test("homepage follows the approved brand-first story and has working CTA targets",async()=>{const html=await (await render()).text();for(const value of ["Minder regelen.","Meer verenigen.","Herkenbaar?","Alles op één plek","Slimmer werken","/platform","/contact","mailto:info@meervereniging.nl"]){assert.match(html,new RegExp(value))}const homepageSource=await readFile(new URL("../src/components/homepage-creative.tsx",import.meta.url),"utf8");const homepageContentSource=await readFile(new URL("../src/lib/homepage-content.ts",import.meta.url),"utf8");assert.doesNotMatch(homepageSource,/\/assets\/product\//);assert.doesNotMatch(homepageContentSource,/\/assets\/product\//);assert.doesNotMatch(homepageSource,/drinkLines|DRANKENLIJST/);assert.equal((html.match(/class="mv-compressed-[^"]+"/g)??[]).length,7);assert.doesNotMatch(html,/Echte productbeelden|TODO: approved real product screenshot|100\+ verenigingen|4,8 uit 5|href="#"|href=""/i)});
test("public routes render without price amounts",async()=>{for(const path of ["/platform","/modules","/voor-wie","/prijzen","/over-ons","/contact","/privacy","/cookies","/algemene-voorwaarden","/beveiliging","/data-opslag","/waarom-meer-vereniging"]){const response=await render(path);assert.equal(response.status,200,path);const html=await response.text();assert.doesNotMatch(html,/24,95|44,95|99,95|lanceerprijs/i)}});
test("public shell has links for logo, footer and official contact",async()=>{const html=await (await render()).text();assert.match(html,/aria-label="Meer Vereniging, ga naar de homepage"/);assert.match(html,/href="mailto:info@meervereniging.nl"/);const siteConfigSource=await readFile(new URL("../src/config/site.ts",import.meta.url),"utf8");const navHrefs=[...siteConfigSource.matchAll(/\['[^']*',\s*'([^']+)'\]/g)].map((match)=>match[1]);assert.equal(navHrefs.length,4,"verwacht de 4 huidige navigatie-items uit site.ts (De app / Prijzen / Waarom Meer Vereniging? / Over ons & contact)");for(const path of [...navHrefs,"/privacy","/cookies","/algemene-voorwaarden","/beveiliging","/data-opslag"]){assert.match(html,new RegExp(`href="${path}"`))}});
test("content architecture retains repository boundary",async()=>{const local=await readFile(new URL("../src/repositories/local.ts",import.meta.url),"utf8");assert.match(local,/localPages/);assert.match(local,/localModules/)});
test("secure CMS preview has an explicit routable path",async()=>{const route=await readFile(new URL("../app/cms-preview/page.tsx",import.meta.url),"utf8");const config=JSON.parse(await readFile(new URL("../vercel.json",import.meta.url),"utf8"));assert.match(route,/CmsPreviewPage/);assert.deepEqual(config.rewrites.find((rewrite)=>rewrite.source==="/_cms-preview"),{source:"/_cms-preview",destination:"/cms-preview"});const response=await render("/cms-preview");assert.equal(response.status,200);assert.match(await response.text(),/Voorbeeld niet beschikbaar/) });
test("unknown nested commercial routes return a 404 instead of a legacy fallback",async()=>{const response=await render("/sport/onbekend");assert.equal(response.status,404)});
