-- Activation template: apply only in a configured Supabase project.
create table sites (id uuid primary key default gen_random_uuid(), name text not null, domain text unique, created_at timestamptz not null default now());
create table organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table pages (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id), slug text not null, title text not null, status text not null check (status in ('draft','published','archived')), seo_title text, seo_description text, updated_at timestamptz not null default now(), unique(site_id,slug));
create table page_sections (id uuid primary key default gen_random_uuid(), page_id uuid not null references pages(id) on delete cascade, type text not null, sort_order integer not null, content jsonb not null default '{}'::jsonb, settings jsonb not null default '{}'::jsonb, visible boolean not null default true);
create table modules (id uuid primary key default gen_random_uuid(), site_id uuid references sites(id), slug text not null, name text not null, status text not null, content jsonb not null default '{}'::jsonb, unique(site_id,slug));
create table articles (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id), slug text not null, title text not null, content text not null, status text not null, published_at timestamptz, unique(site_id,slug));
create table leads (id uuid primary key default gen_random_uuid(), site_id uuid references sites(id), kind text not null, email text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id), actor_id uuid, action text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table pages enable row level security; alter table page_sections enable row level security; alter table modules enable row level security; alter table articles enable row level security; alter table leads enable row level security;
